{{- if .Values.autoscaling.vpa.enabled }}
apiVersion: autoscaling.k8s.io/v1
kind: VerticalPodAutoscaler
metadata:
  name: {{ include "common.names.fullname" . }}
  namespace: {{ include "common.names.namespace" . | quote }}
  labels: {{- include "common.labels.standard" (dict "customLabels" .Values.commonLabels "context" $) | nindent 4 }}
    app.kubernetes.io/component: __CHART__
  {{- if or .Values.autoscaling.vpa.annotations .Values.commonAnnotations }}
  {{- $annotations := include "common.tplvalues.merge" (dict "values" (list .Values.autoscaling.vpa.annotations .Values.commonAnnotations) "context" .) }}
  annotations: {{- include "common.tplvalues.render" (dict "value" $annotations "context" $) | nindent 4 }}
  {{- end }}
spec:
  targetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: {{ include "common.names.fullname" . }}
  updatePolicy:
    updateMode: {{ .Values.autoscaling.vpa.updatePolicy.updateMode | quote }}
  {{- if or .Values.autoscaling.vpa.controlledResources .Values.autoscaling.vpa.minAllowed .Values.autoscaling.vpa.maxAllowed }}
  resourcePolicy:
    containerPolicies:
      - containerName: {{ .Chart.Name }}
        {{- if .Values.autoscaling.vpa.controlledResources }}
        controlledResources: {{- toYaml .Values.autoscaling.vpa.controlledResources | nindent 10 }}
        {{- end }}
        {{- if .Values.autoscaling.vpa.minAllowed }}
        minAllowed: {{- toYaml .Values.autoscaling.vpa.minAllowed | nindent 10 }}
        {{- end }}
        {{- if .Values.autoscaling.vpa.maxAllowed }}
        maxAllowed: {{- toYaml .Values.autoscaling.vpa.maxAllowed | nindent 10 }}
        {{- end }}
  {{- end }}
{{- end }}
