apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "keeweb.fullname" . }}-nginx
  labels:
    {{- include "keeweb.labels" . | nindent 4 }}
data:
  keeweb.conf: |
    server {
        listen {{ .Values.service.httpPort }} default_server;
        server_name _;
        root /keeweb;
        index index.html;

        server_tokens off;
        add_header X-Content-Type-Options nosniff;

        location / {
            try_files $uri $uri/ =404;
        }

        location ~ /\. {
            deny all;
        }
    }
