apiVersion: v2
name: fan-control
description: Lenovo RD450x fan control
type: application
annotations:
  licenses: MIT License
home: https://github.com/mixa3607/charts/tree/master/charts/fan-control
icon: https://raw.githubusercontent.com/mixa3607/charts/refs/heads/master/charts/fan-control/icon.png
keywords: []
maintainers:
  - name: mixa3607
    url: https://github.com/mixa3607
sources:
  - https://github.com/mixa3607/fan-control
version: 0.2.1
appVersion: 0.2.2
dependencies:
  - name: bitnami-common
    repository: oci://ghcr.io/mixa3607/charts
    tags:
      - bitnami-common
    version: 2.x.x
