apiVersion: v2
name: ztnet
description: ZTNET - ZeroTier Web UI for Private Controllers with Multiuser and Organization Support.
type: application
annotations:
  licenses: MIT License
home: https://github.com/mixa3607/charts/tree/master/charts/ztnet
icon: https://raw.githubusercontent.com/mixa3607/charts/refs/heads/master/charts/ztnet/icon.png
keywords: []
maintainers:
  - name: mixa3607
    url: https://github.com/mixa3607/charts/charts/ztnet
sources:
  - https://github.com/sinamics/ztnet
version: 0.1.3
appVersion: 0.8.5
dependencies:
  - name: bitnami-common
    repository: oci://ghcr.io/mixa3607/charts
    tags:
      - bitnami-common
    version: 2.x.x
